const q=document.getElementById("question"),ask=document.getElementById("askBtn"),answer=document.getElementById("answer"),photo=document.getElementById("photoInput"),micBtn=document.getElementById("micBtn");
function setLoading(){answer.className="answer";answer.innerHTML='<div class="question-label">AI TUTOR</div><div class="answer-title">AI जवाब तैयार कर रहा है…</div><div class="answer-text">थोड़ा इंतज़ार करें…</div>';answer.scrollIntoView({behavior:"smooth",block:"center"})}
function showAnswer(text){answer.className="answer";answer.innerHTML=`<div class="question-label">AI TUTOR</div><div class="answer-title">${escapeHtml(text||"AI Tutor")}</div><div class="answer-text">AI से जवाब पाने के लिए अपना सवाल भेजें।</div>`}
async function askAI(text,imageData=null){const question=(text||"").trim();if(!question&&!imageData)return;setLoading();ask.disabled=true;try{const response=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question,image:imageData})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||"AI service unavailable");answer.className="answer";answer.innerHTML=`<div class="question-label">AI TUTOR • LIVE</div><div class="answer-title">आपके सवाल का जवाब</div><div class="answer-text">${formatAnswer(data.answer||"कोई जवाब नहीं मिला।")}</div><span class="tag">Hindi + English</span><span class="tag">Step-by-step</span>`;answer.scrollIntoView({behavior:"smooth",block:"center"})}catch(err){answer.className="answer";answer.innerHTML=`<div class="question-label">AI TUTOR</div><div class="answer-title">AI connect नहीं हो पाया</div><div class="answer-text">${escapeHtml(err.message||"कृपया बाद में फिर कोशिश करें।")}</div><p style="margin-top:12px;color:#687572"><b>Next:</b> Vercel पर backend deploy करके OPENAI_API_KEY जोड़ना जरूरी है।</p>`}finally{ask.disabled=false}}
function formatAnswer(text){return escapeHtml(text).replace(/\*\*(.*?)\*\*/g,"<strong>$1</strong>").replace(/\n/g,"<br>")}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
ask.onclick=()=>{const text=q.value.trim();if(!text){q.focus();q.placeholder="पहले अपना सवाल लिखें…";return}askAI(text)};
q.addEventListener("keydown",e=>{if(e.key==="Enter")ask.click()});
document.querySelectorAll("[data-q]").forEach(b=>b.onclick=()=>{q.value=b.dataset.q;ask.click()});
document.querySelectorAll(".course").forEach(b=>b.onclick=()=>{q.value=`${b.dataset.course} के लिए मुझे पढ़ाई शुरू करने का आसान plan और important topics बताओ`;ask.click()});
document.getElementById("photoTool").onclick=()=>photo.click();
photo.onchange=()=>{const file=photo.files?.[0];if(!file)return;if(!file.type.startsWith("image/"))return;if(file.size>8*1024*1024){showAnswer("Photo बहुत बड़ी है — 8 MB से छोटी photo चुनें।");return}const reader=new FileReader();reader.onload=()=>askAI(q.value.trim()||"इस फोटो में दिए सवाल को पढ़कर आसान भाषा में step-by-step हल करो।",reader.result);reader.readAsDataURL(file)};
micBtn.onclick=()=>{const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SpeechRecognition){q.placeholder="इस browser में voice typing उपलब्ध नहीं है। Keyboard का mic इस्तेमाल करें।";q.focus();return}const recognition=new SpeechRecognition();recognition.lang="hi-IN";recognition.interimResults=false;recognition.maxAlternatives=1;micBtn.textContent="⏺️";recognition.onresult=e=>{q.value=e.results[0][0].transcript};recognition.onerror=()=>{};recognition.onend=()=>{micBtn.textContent="🎙️"};recognition.start()};
document.getElementById("langBtn").onclick=()=>{const btn=document.getElementById("langBtn");btn.textContent=btn.textContent==="हि"?"EN":"हि";q.placeholder=btn.textContent==="EN"?"Ask your study question…":"अपनी पढ़ाई का सवाल लिखें…"};
document.querySelectorAll(".nav").forEach(n=>n.onclick=()=>{document.querySelectorAll(".nav").forEach(x=>x.classList.remove("active"));n.classList.add("active");if(n.dataset.page==="tutor")q.focus();else if(n.dataset.page==="courses")document.querySelector(".course-grid").scrollIntoView({behavior:"smooth"});else if(n.dataset.page==="practice"){q.value="मुझे 10 questions का practice quiz बनाओ";ask.click()}else if(n.dataset.page==="profile")showAnswer("Student Profile")});
